### ISSUE TITLE
Embed doesn't load wide enough

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune-image-slider#10]
When embedded in a post, the image slider should take up the entire body width. On most verticals it has a tiny bit of padding on either side.

On polygon, there's a lot of extra space:
![image](https://cloud.githubusercontent.com/assets/5759653/7776511/7d55f2b0-0089-11e5-9d49-ef2d31364083.png)

Vox.com example: http://vox.sb12.sbndev.net/2015/5/22/8003386/hey-im-a-headline
Polygon example: http://polygon.sb12.sbndev.net/2015/5/22/8003388/beep-beep

Expected: Embed takes entire width of body (changes depending on the vertical). If we need a bit of padding for any reason, next best solution is to get polygon to match other verticals.

**Comment by caseymm** [comment]
So, looks like that's only happening to these two verticals after the latest fix:

Racked: http://racked.sb6.sbndev.net/2015/5/22/8003435/headline
Polygon example: http://polygon.sb12.sbndev.net/2015/5/22/8003388/beep-beep

Looks like that column width is being set by the vertical, though, so I'm not sure what we can do to get around that.

![screen shot 2015-05-22 at 2 29 39 pm](https://cloud.githubusercontent.com/assets/3526984/7777243/4f871200-008f-11e5-8bde-23c81d999179.png)
![screen shot 2015-05-22 at 2 27 53 pm](https://cloud.githubusercontent.com/assets/3526984/7777247/61fb2d7c-008f-11e5-8f88-742386962397.png)

**Comment by kelseyscherer** [comment]
Ah, I didn't realize that Polygons text only took up a percentage of that space as well! I'm fine with polygon being this way since the image will line up with the text.

Re: Racked — We have body text that takes up that space within the body column, but when images and videos are embedded, they bump into the left margin space. Ex: http://www.racked.com/2015/5/20/8630635/tess-holliday-people-magazine-cover
![image](https://cloud.githubusercontent.com/assets/5759653/7777318/181cf28e-0090-11e5-8e45-d3010fd628ca.png)
Note how the embedded image is wider than the text.

Ideally, it would be cool for image sliders to behave the same way images do on racked, but is not necessary for this iteration of the image slider.
