### ISSUE TITLE
Need to better style the image credits

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune-image-slider#12]
![screen shot 2015-06-03 at 2 41 36 pm](https://cloud.githubusercontent.com/assets/222285/7968411/b274f22e-09fe-11e5-9f1d-282b5a1e501d.png)

This might require making themes for each site (to account for font size and link color), which we had previously avoided for this blueprint. 

Alternatively, we could define one link style for all (smaller type, underlinked gray link?). But I differ to @kelseyscherer.

**Comment by kelseyscherer** [comment]
Let's stick with one style for this, but we can make it look a bit nicer:
- [x] 12px size
- [x] `Source:` and `and` get color: #363637
- [x] Links underlined
- [x] sources get color: #6B6B6B
