### ISSUE TITLE
Use caption styles from framework/foundation that we've defined for each vertical

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune-image-slider#16]
Because as seen in this article, mixing a slider with normal photos results in very irregular caption styles: http://www.vox.com/2015/6/15/8774475/renaissance-art-tracing-cartoons

**Comment by kelseyscherer** [comment]
we should use styles defined in our framework / foundation for captions :speak_no_evil: 

the captions still wouldn't match fully, but they'd at least be in the same fonts. Thoughts, @laurenrabaino?

**Comment by laurenrabaino** [comment]
:+1:

**Comment by kelseyscherer** [comment]
cool. updated name of issue

**Comment by kelseyscherer** [comment]
we're gonna use caption styles defined on charts and tables, and will be done as part of the work to upgrade image slider to use foundation.
