### ISSUE TITLE
When embedded on Verge, image slider does some whacky stuff

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune-image-slider#7]
The left image is shorter than the right image. 
After sliding 75% right, the left image grows in size. 

Example link:
http://www.theverge.com/verge_entries/preview/8383976

Screenshot:
http://cl.ly/image/1T2w2v3L200z/Screen%20Shot%202015-05-18%20at%2010.19.44%20AM.png

**Comment by aithnefeay** [comment]
The main reason this looks awkward is because the zombie photo has a white border. Images only grow when their standard resolution is not wide enough to fill the whole window without stretching.

**Comment by laurenrabaino** [comment]
So we should either restrict the min-width allowed, or force stretch the smaller images to fill the whole window. I vote for the latter.

**Comment by aithnefeay** [comment]
Conversation with @laurenrabaino: Looks like it's an image size issue, this only occurs with smaller images. Need to find a solution to start with the image stretched (possibly calc a min resolution based on window size) or warn in the project editor that your images must be at least x tall and as wide as the container you're putting them in.

**Comment by caseymm** [comment]
Talked to @alfeay about this issue and we agree that it's probably best to leave as is for now. This behavior is identical to that of the existing image slider and forcing small images to be 100% width would likely result in some really grainy images. Ideally, it'd be great if we could restrict the sizes of images that people are allowed to upload. Unfortunately we'd need to be able to detect information about each image's properties to do so during the form submission process, which is not currently within the scope of project creation in Autotune.

**Comment by laurenrabaino** [comment]
Can we add to the instructions some helper text about minimum width?

**Comment by caseymm** [comment]
Yes. I can add some suggestions about image size to the helper text.
